const fs = require('fs');
const directory = `templates/${process.argv[2]}`;

const pugFile =
`//- DO NOT EDIT THIS FILE

doctype html
html
  head
    style
      include ../styles.scss
  body
    include ../template.pug
    script(src='/script.js')
`;

const configFile =
`// DO NOT EDIT THIS FILE

const data = require('../data');

module.exports = {
  locals: data
};
`;

const stylesFile =
`h1 {
  color: red
}`;

const templateFile =
`//- Keep this line for correctly building PDFs
style(type="text/css") !{compiledStyle}

h1 #{message}`;

const dataFile =
`module.exports = {
  // data goes here...
  message: 'Hello world!'
};`;

if (!fs.existsSync(directory)){
  fs.mkdirSync(directory);
  fs.mkdirSync(`${directory}/build`);

  fs.writeFile(`${directory}/build/index.pug`, pugFile, () => {
    console.log(`Successfully wrote ${directory}/index.pug`);
    fs.writeFile(`${directory}/build/pug.config.js`, configFile, () => {
      console.log(`Successfully wrote ${directory}/pug.config.js`);
      fs.writeFile(`${directory}/build/script.js`, '', () => {
        console.log(`Successfully wrote ${directory}/build/script.js`);
        fs.writeFile(`${directory}/template.pug`, templateFile, () => {
          console.log(`Successfully wrote ${directory}/template.pug`);
          fs.writeFile(`${directory}/styles.scss`, stylesFile, () => {
            console.log(`Successfully wrote ${directory}/styles.scss`);
            fs.writeFile(`${directory}/data.js`, dataFile, () => {
              console.log(`Successfully wrote ${directory}/data.js`);
              console.log('\n\n To view your template, run the following command:')
              console.log(`\n\n parcel ${directory}/build/index.pug \n\n`);
            });
          });
        });
      });
    });
  });
} else {
  console.warn(`${directory} already exists`);
}
